# Generated by Django 5.0.7 on 2024-07-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=100),
        ),
    ]
