# Generated by Django 5.0.7 on 2024-07-18 11:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
